# Generated by Django 5.2.7 on 2025-10-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.TextField(
                blank=True, help_text="Enter your career interests and goals"
            ),
        ),
    ]
